sudo: required
dist: trusty

language: java
jdk: oraclejdk8
before_install: echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g'" > ~/.mavenrc

install: true
script:
  - mvn clean install -B -V -f server/pom.xml
